### ISSUE TITLE
Pipeline Tab API Integration - Hubspot

### ISSUE THREAD

**Issue by RichardJamesLopez** [RichardJamesLopez/app-nesting#25]
Creating a Hubspot API for REST access to Ourmada

- [x] Create a Private App on codypomeray01@gmail.com 's Hubspot account
- [x] Meant to have Read access to CRM->Deals table 
![Image](https://github.com/RichardJamesLopez/app-nesting/assets/8483531/42a939dc-8495-4f94-8750-74a4484880c8)

- [x] Retrieved App Token from Hubspot app
- [x] Added Token value to Vercel Env variables titled `HUBSPOT_TOKEN_1`
- [ ] Create a file in latest code w/ a page view of Hubspot data

**Comment by RichardJamesLopez** [comment]
@nmwur I now have a separate API for hubspot data. 

**_How would you advise we surface this data in the current app?_** Should it be a separate tab item, or a different type of `pipeline` available to the user? 

If we create a skeleton page with the proper UI/UX, I can attempt to feed Hubspot data into a table in a similar way we do Notion data.

**Comment by nmwur** [comment]
should there be only one api integration per organization (hubspot/notion/etc)?
if so, i think we could just surface the pipeline type in the **Custom rules page** in Settings (#19).

otherwise, we could still try to encapsulate data source selection logic in Settings by having multiple **Custom rules tabs**, each per source, and enabling admins to converge multiple data sources into one table for members to see in the Pipeline page.

am i on the right track?

**Comment by RichardJamesLopez** [comment]
What is the difference of effort it would take to do this: 

> otherwise, we could still try to encapsulate data source selection logic in Settings by having multiple Custom rules tabs, each per source, and enabling admins to converge multiple data sources into one table for members to see in the Pipeline page.
 
vs

> should there be only one api integration per organization (hubspot/notion/etc)?
if so, i think we could just surface the pipeline type in the Custom rules page in Settings

The former seems like the more elegant solution, but let's scope out how different these solutions are first.

**Comment by nmwur** [comment]
agree, also the former solution seems easier to manage since each Customer would have a unique set of fields from their data source anyway


the difference between these two solutions:
|             | one API per Customer                                         | multiple APIs per Customer                                   |
|-------------|--------------------------------------------------------------|--------------------------------------------------------------|
| our efforts | manually setting column names in database on:<br>- Customer onboarding<br>- Customer changing a column name in their data source | adding:<br>- column mapping ui<br>- respective database tables |


here is a rough mockup of how the column mapping ui for admins could look like. i'd like to learn more how this aligns with the Custom rules functionality (#19)
<img width="881" alt="image" src="https://github.com/RichardJamesLopez/app-nesting/assets/22333399/9520699a-b97a-416e-b598-27016b3b12e0">

**Comment by RichardJamesLopez** [comment]
Re: Mockup - I think it looks quite good. I made 2 comments in this version: 
![image](https://github.com/RichardJamesLopez/app-nesting/assets/8483531/14440249-6982-498a-9d67-1beb362a99f9)

Re: 

> i'd like to learn more how this aligns with the Custom rules functionality (https://github.com/RichardJamesLopez/app-nesting/issues/19)i'd like to learn more how this aligns with the Custom rules functionality (https://github.com/RichardJamesLopez/app-nesting/issues/19)

API integration (and maintinance) and Custom Rules Issue 19 go hand in hand. I actually think after the initial setup they should probably be on the same page (they should align quite perfectly and is convenient to the admin to adjust everything on the same page)

However, for the initial setup I am open to hearing your thoughts on how it would be to execute. I see the pro of having everything on 1 page as being convenience, and only a single page to maintain. The con is that the business logic can get overly complex.

**Comment by RichardJamesLopez** [comment]
Update on my end: 

- added new files for `DealRouter_Hubspot.ts` and `hubspot.ts` on local machine. 
- Updated `package.json` and `env.js` to install https://www.npmjs.com/package/@hubspot/api-client

Still to do: 
- add log messages to see if current `HubspotActivity` is flowing through

**Comment by nmwur** [comment]
>API integration (and maintinance) and Custom Rules Issue 19 go hand in hand. I actually think after the initial setup they should probably be on the same page (they should align quite perfectly and is convenient to the admin to adjust everything on the same page)

i see! and since there is no need for hardcoded "Ourmada columns" as the single point of integration across the APIs, maybe we could even prepend Custom Rules to the Pipeline page as a toggle-open panel for admins.
i'll also think about the initial setup flow

**Comment by RichardJamesLopez** [comment]
@nmwur Can I reassign this task formally to you? 

I can send you the files that I worked on, and we can keep the comment history for posterity's sake.

**Comment by RichardJamesLopez** [comment]
FYI - Added a new column for "Visibility" which is a `property` under the `deal information` card of a `deal`. 

Right now, I have a single deal assigned to each of the following 3 values: 
- Full Visibility
- Custom Visibility
- Hidden


The rest of the deals do not have a value assigned to them yet.

**Comment by nmwur** [comment]
update:
- the Pipeline page is under construction

question:
- i forgot, should there be a default "Visibility" value for `null`?

![Image](https://github.com/RichardJamesLopez/app-nesting/assets/22333399/d5ad7064-90b8-4dc2-8d75-1d8dabe0a8c9)

**Comment by RichardJamesLopez** [comment]
When we have the Visibility Default option, then all null values should be that selection option. @nmwur 

Until then, I am fine w/ Null. (for this particular db, I'll make sure to go through each one and select a visibility setting.

**Comment by nmwur** [comment]
todo:

- [ ] populate individual deal's page
- [ ] apply visibility to Pipeline based on api
- [ ] add "deal owner" column
- [ ] add pagination in Pipeline
